/*
 * Copyright (c) 2022, 2023, Oracle and/or its affiliates.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2.0, as
 * published by the Free Software Foundation.
 *
 * This program is also distributed with certain software (including
 * but not limited to OpenSSL) that is licensed under separate terms,
 * as designated in a particular file or component or in included license
 * documentation.  The authors of MySQL hereby grant you an
 * additional permission to link the program and your derivative works
 * with the separately licensed software that they have included with
 * MySQL.
 *
 * Without limiting anything contained in the foregoing, this file,
 * which is part of MySQL Connector/Node.js, is also subject to the
 * Universal FOSS Exception, version 1.0, a copy of which can be found at
 * http://oss.oracle.com/licenses/universal-foss-exception.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License, version 2.0, for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
 */

import { int64 } from '../Protocol/ScalarValues';
import RowResult from './RowResult';

/**
 * Result set type generated by executing SQL statements with `Session.sql()`.
 */
interface SqlResult extends RowResult {
    /**
     * Retrieves the number of items affected by the statement.
     * @returns The total number of items affected by the statement.
     */
    getAffectedItemsCount: () => int64
    /**
     * Retrieves the first `AUTO INCREMENT` value generated by the statement.
     * @returns The first `AUTO INCREMENT` value.
     */
    getAutoIncrementValue: () => int64
    /**
     * Checks if the current result set contains additional data to be consumed.
     * @returns A boolean that is `true` if there is still data to be consumed.
     * Otherwise returns `false`.
     */
    hasData: () => boolean
    /**
     * Checks if there are more result sets to be consumed.
     * @returns A boolean that is `true` if there are additional result sets
     * to be consumed. Otherwise returns `false`.
     */
    nextResult: () => boolean
}

export default SqlResult;
